### ISSUE TITLE
Working very well.... need more informations

### ISSUE THREAD

**Issue by hfrance** [Wohlstand/PHP-SMTP-Mail-Sender#1]
Hi sir, this is not really a issue.

I have a cpanel with root access.

Everything is working fine but i am interested to check the respond of the smtp receiver.

at this moment I check manually the smtp receiver by the mail queue of cpanel.

it possible to do something in php to check the receive status, just give me some idea, I going to check after.

thank you

**Comment by Wohlstand** [comment]
That needs for a small update to add the header which tells that letter needs a delivery/reading confirmation

**Comment by hfrance** [comment]
humm.. not really the email receiver but the smtp receive, like if the email exist, like is passed or block for spam ...

**Comment by Wohlstand** [comment]
Ah, you mean that to receive letter back? You need a pop3/imap client to receive letters. SMTP can only send, and the SMTP server may reject sending if some local criteria didn't pass. When remote server rejects a letter, it will send back a letter with a report that you can receive by pop3/imap only.

**Comment by Wohlstand** [comment]
Also, local SMTP server sends back a report letter when it doesn't able to connect to a remote mail server

**Comment by Wohlstand** [comment]
Anyway, if your SMTP server gives a report about some badness in the time of sending session, just add the handling of your special error reply into the code of script.

**Comment by hfrance** [comment]
In remote smtp, the smtp connexion seen to not close so everytime i connect to the smtp and send email i have a multiplication of the connection to the remote smtp -The server has reached its limit for processing requests from your host

**Comment by Wohlstand** [comment]
I also guess if your smtp server has a queue, it will report about the state by a letter to your mailbox only. The instant report about remote server (server of receipient's mailbox) side errors and rejects is only possible when no queue being used. Also this may hang for a while. Queue is also used to keep letters for a time when remote server is down or unavailable for temporary. And if server gets online back,  the letter is sending to it from a queue. Otherwise, your local server will report a timeout error by a back letter.

**Comment by hfrance** [comment]
Hi sir, thank for your anwser, i just find the respond on the server with grep

 'grep -i "'.$email.' R=dkim_lookuphost.*250.*" /var/log/exim_mainlog'
